## 2. 넘파이로 텐서 만들기(벡터와 행렬 만들기)

In [2]:
import numpy as np

### 1) 1D with Numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ', t.ndim) #차원수
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


#### 1-1) Numpy 기초 이해하기

In [5]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [6]:
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다.

t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]


In [ ]:
print('t[:2] t[3:]     = ', t[:2], t[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우 끝번호 일때는 n-1 까지

t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


## 3. 파이토치 텐서 선언하기(PyTorch Tensor Allocation)

In [3]:
import torch

### 1) 1D with PyTorch

In [4]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.]) #32비트 텐서가 기본
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [5]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [6]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2) 2D with PyTorch

In [7]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [8]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [ ]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 인덱스 1 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [15]:
print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### 3) 브로드캐스팅(Broadcasting)

In [16]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [ ]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3], 확장 추가
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]]) # 자동 확장됨
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## 4. 자주 사용되는 기능들

### 1) 행렬 곱셈과 곱셈의 차이(Matrix Multiplication Vs. Multiplication)

In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1 행렬 곱셈
'''
선형변환, 신경망 레이어
'''

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) #원소끼리 곱
'''
가중치 스케일링, 마스킹
'''

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 2) 평균(Mean)

In [10]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [11]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [12]:
print(t.mean())

tensor(2.5000)


In [13]:
print(t.mean(dim=0))

tensor([2., 3.])


shape = (2, 3, 4, 5)
         ↑  ↑  ↑  ↑
         0  1  2  3  ← dim 번호

shape (2, 3, 4, 5)  →  mean(dim=0)  →  shape (3, 4, 5)    # 2가 사라짐
shape (2, 3, 4, 5)  →  mean(dim=1)  →  shape (2, 4, 5)    # 3이 사라짐
shape (2, 3, 4, 5)  →  mean(dim=2)  →  shape (2, 3, 5)    # 4가 사라짐
shape (2, 3, 4, 5)  →  mean(dim=3)  →  shape (2, 3, 4)    # 5가 사라짐

즉 기준 삼는 dim 이 사라진다 생각하고 연산

In [14]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [15]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


### 3) 덧셈(Sum)

In [27]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


이때 "모든 이미지의 평균을 구하고 싶다"면? → 배치를 없애야 하니까 → mean(dim=0) — 끝입니다.

"RGB 채널을 합쳐서 흑백으로 만들고 싶다"면? → 채널을 없애야 하니까 → mean(dim=1) — 끝입니다.

숫자가 어떻게 계산되는지는 신경 쓸 필요 없습니다. "어떤 축을 없앨 것인가"만 생각.

### 4) 최대(Max)와 아그맥스(ArgMax)

최대(Max)는 원소의 최대값을 리턴하고, 아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴

In [16]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [17]:
print(t.max()) # Returns one value: max

tensor(4.)


In [ ]:
print(t.max(dim=0)) # Returns two values: max and argmax, 행방향 즉 위아래

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [ ]:
print('Max: ', t.max(dim=0)[0]) #최대값 그 자체
print('Argmax: ', t.max(dim=0)[1]) #각 최대값 인덱스

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [33]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### 5) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!


In [20]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [21]:
print(ft.shape) #3차 이상 텐서는 덩어리 순서로 표현

torch.Size([2, 2, 3])


In [22]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [23]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 6) 스퀴즈(Squeeze) - 1인 차원을 제거한다.

In [24]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [25]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### 7) 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

t = torch.FloatTensor([1, 2, 3])
print(t.shape)                # (3,) #shape 은 튜플로 저장

print(t.unsqueeze(0).shape)   # (1, 3)  ← 앞에 추가
print(t.unsqueeze(1).shape)   # (3, 1)  ← 뒤에 추가, 즉 인덱스 1인 위치에 추가
```
```
[1, 2, 3]       →    [[1, 2, 3]]
(3,)                  (1, 3)

[1, 2, 3]       →    [[1],
(3,)                   [2],
                       [3]]
                      (3, 1)

In [40]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [41]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [42]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [43]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [44]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### 8) 타입 캐스팅(Type Casting)

텐서의 데이터 타입을 바꾸는 것
LongTensor: 64비트 정수형 텐서
소수점이 없는 정수만 저장 -> 원 데이터가 소수점이였으면 소수점 없애줌 

In [45]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [46]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [47]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [ ]:
print(bt.long()) #.long() -> 기존 있는 텐서를 longtensor 로 변환
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### 9) 연결하기(concatenate)

In [49]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [ ]:
print(torch.cat([x, y], dim=0)) #dim=0 기준이면 위아래로 연결

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [ ]:
print(torch.cat([x, y], dim=1)) #dim=-1 기준이면 양옆으로 연결

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### 10) 스택킹(Stacking)

In [52]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [53]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [54]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.stack([x, y, z], dim=1)) #무조건 쌓는건데 열방향이니까 cat 과 반대로 위아래로 "쌓게" 됨

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### 11) ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서


In [56]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [57]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [58]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 12) In-place Operation (덮어쓰기 연산)

일반 연산	In-Place 버전	의미
x.add(2)	x.add_(2)	더하기
x.sub(2)	x.sub_(2)	빼기
x.mul(2)	x.mul_(2)	곱하기
x.div(2)	x.div_(2)	나누기
x.zero()	x.zero_()	0으로 채우기
x.fill(5)	x.fill_(5)	특정 값으로 채우기
x.abs()	x.abs_()	절대값
x.clamp(0,1)	x.clamp_(0,1)	범위 제한
x.round()	x.round_()	반올림

In [26]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [ ]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [61]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


객체 연산 부분 중 헷갈렸던 부분

class Calculator:
    def __init__(self): # 객체 생성 시 호출될 때 실행되는 초기화 함수. 이를 생성자라고 한다.
        self.result = 0

    def add(self, num): # 객체 생성 후 사용할 수 있는 함수.
        self.result += num
        return self.result

이렇게 class 구현 한 다음 이걸 받을 객체 만듦 
cal1 = Calculator()
class 호출 하고 나면 
cal1.add(3) 
이걸로 class 내 메서드 다 부를수 있음음